//! Phase 2.3 foundation: Host-side "ZK-Supreme Court" verifier (RISC Zero API shape).
//!
//! Guest compilation may be bypassed via `RISC0_SKIP_BUILD=1`.

use base64::Engine as _;
pub use nexus_protocol::InferenceJournalV1;
use risc0_zkvm::Receipt;

pub fn verify_receipt(receipt_b64: &str) -> anyhow::Result<bool> {
    Ok(verify_receipt_with_size(receipt_b64)?.0)
}

pub fn verify_receipt_with_size(receipt_b64: &str) -> anyhow::Result<(bool, usize)> {
    // Dev-mode mock receipt: encoded `InferenceJournalV1` (no cryptographic proof).
    if let Some(rest) = receipt_b64.strip_prefix("MOCKJ1:") {
        let bytes = base64::engine::general_purpose::STANDARD
            .decode(rest.as_bytes())
            .map_err(|e| anyhow::anyhow!("Failed to decode MOCKJ1 b64: {e}"))?;
        // Validate it at least deserializes.
        let _j: InferenceJournalV1 = bincode::deserialize(&bytes)
            .map_err(|e| anyhow::anyhow!("Failed to deserialize MOCKJ1 journal: {e}"))?;
        return Ok((true, bytes.len()));
    }

    // 1. Decode base64
    let receipt_bytes = base64::engine::general_purpose::STANDARD
        .decode(receipt_b64.as_bytes())
        .map_err(|e| anyhow::anyhow!("Failed to decode receipt b64: {e}"))?;
    let proof_size = receipt_bytes.len();

    // 2. Deserialize into RISC Zero Receipt
    let receipt: Receipt = bincode::deserialize(&receipt_bytes)
        .map_err(|e| anyhow::anyhow!("Failed to deserialize receipt: {}", e))?;

    // 3. Verify against the Image ID (generated by `methods` crate).
    let image_id = methods::NEXUS_GUEST_ID;
    match receipt.verify(image_id) {
        Ok(_) => Ok((true, proof_size)),
        Err(e) => {
            log::error!("ZK Verification Math Failed: {:?}", e);
            Ok((false, proof_size))
        }
    }
}

#[allow(dead_code)]
pub fn verify_and_extract_inference_journal(
    receipt_b64: &str,
) -> anyhow::Result<InferenceJournalV1> {
    if let Some(rest) = receipt_b64.strip_prefix("MOCKJ1:") {
        let bytes = base64::engine::general_purpose::STANDARD
            .decode(rest.as_bytes())
            .map_err(|e| anyhow::anyhow!("Failed to decode MOCKJ1 b64: {e}"))?;
        let j: InferenceJournalV1 = bincode::deserialize(&bytes)
            .map_err(|e| anyhow::anyhow!("Failed to deserialize MOCKJ1 journal: {e}"))?;
        return Ok(j);
    }
    let receipt_bytes = base64::engine::general_purpose::STANDARD
        .decode(receipt_b64.as_bytes())
        .map_err(|e| anyhow::anyhow!("Failed to decode receipt b64: {e}"))?;
    let receipt: Receipt = bincode::deserialize(&receipt_bytes)
        .map_err(|e| anyhow::anyhow!("Failed to deserialize receipt: {}", e))?;

    // Verify first: do not decode untrusted journal before cryptographic verification.
    let image_id = methods::NEXUS_GUEST_ID;
    receipt
        .verify(image_id)
        .map_err(|e| anyhow::anyhow!("ZK Verification Math Failed: {e:?}"))?;

    receipt
        .journal
        .decode()
        .map_err(|e| anyhow::anyhow!("Failed to decode inference journal: {e:?}"))
}

pub fn verify_and_extract_inference_journal_with_size(
    receipt_b64: &str,
) -> anyhow::Result<(InferenceJournalV1, usize)> {
    if let Some(rest) = receipt_b64.strip_prefix("MOCKJ1:") {
        let bytes = base64::engine::general_purpose::STANDARD
            .decode(rest.as_bytes())
            .map_err(|e| anyhow::anyhow!("Failed to decode MOCKJ1 b64: {e}"))?;
        let proof_size = bytes.len();
        let j: InferenceJournalV1 = bincode::deserialize(&bytes)
            .map_err(|e| anyhow::anyhow!("Failed to deserialize MOCKJ1 journal: {e}"))?;
        return Ok((j, proof_size));
    }
    let receipt_bytes = base64::engine::general_purpose::STANDARD
        .decode(receipt_b64.as_bytes())
        .map_err(|e| anyhow::anyhow!("Failed to decode receipt b64: {e}"))?;
    let proof_size = receipt_bytes.len();
    let receipt: Receipt = bincode::deserialize(&receipt_bytes)
        .map_err(|e| anyhow::anyhow!("Failed to deserialize receipt: {}", e))?;

    let image_id = methods::NEXUS_GUEST_ID;
    receipt
        .verify(image_id)
        .map_err(|e| anyhow::anyhow!("ZK Verification Math Failed: {e:?}"))?;

    let journal: InferenceJournalV1 = receipt
        .journal
        .decode()
        .map_err(|e| anyhow::anyhow!("Failed to decode inference journal: {e:?}"))?;
    Ok((journal, proof_size))
}
